name: Apps CI/CD
on: pull_request

jobs:
  coverage_report:
    name: Generate coverage report
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # ... Generate LCOV files or download it from a different job
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage/lcov.info
        minimum-coverage: 10
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # build: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - uses: stelynx/dart-full-coverage@v1.0.5
  #       with:
  #         package: egakcap
  #         ignore: "*_state.dart, do_not_import_me.dart"
  #     - run: flutter pub get
  #     - run: flutter packages pub run build_runner build
  #     - run: flutter build aot
  #     - run: flutter analyze
  #     - run: flutter test --coverage .
  #     - run: genhtml -o coverageReport coverage/lcov.info
  #     - 